# Generated by Django 3.0.5 on 2020-05-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_key', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
