# Generated by Django 3.0.5 on 2020-05-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='developed',
            field=models.IntegerField(default=0),
        ),
    ]
