# Generated by Django 3.0.5 on 2020-05-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0003_room'),
        ('brainwriting', '0004_response_voted'),
    ]

    operations = [
    ]
