# Generated by Django 3.0.5 on 2020-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0005_merge_20200514_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='developed',
            new_name='checked',
        ),
        migrations.RemoveField(
            model_name='response',
            name='nominations',
        ),
        migrations.RemoveField(
            model_name='response',
            name='voted',
        ),
        migrations.AddField(
            model_name='response',
            name='voteNum',
            field=models.IntegerField(default=0),
        ),
    ]
