# Generated by Django 3.0.5 on 2020-05-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0005_merge_20200514_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='room_id',
        ),
    ]
