# Generated by Django 3.0.5 on 2020-06-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0006_auto_20200531_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brainwriting.Room'),
            preserve_default=False,
        ),
    ]
