# Generated by Django 3.0.5 on 2020-05-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0006_auto_20200527_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='checked',
            new_name='check',
        ),
    ]
