# Generated by Django 3.0.5 on 2020-06-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0007_question_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='response',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brainwriting.Room'),
            preserve_default=False,
        ),
    ]
