# Generated by Django 3.0.5 on 2020-06-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0008_auto_20200602_2211'),
        ('brainwriting', '0007_auto_20200527_1346'),
    ]

    operations = [
    ]
