# Generated by Django 3.0.5 on 2020-06-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0007_auto_20200527_1346'),
        ('brainwriting', '0009_room_is_tutorial'),
    ]

    operations = [
    ]
