# Generated by Django 3.0.5 on 2020-06-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0009_merge_20200613_1438'),
        ('brainwriting', '0010_merge_20200607_1606'),
    ]

    operations = [
    ]
