# Generated by Django 3.0.5 on 2020-06-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0011_merge_20200616_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='userList',
            field=models.TextField(default='{}'),
        ),
    ]
