# Generated by Django 3.0.5 on 2020-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0011_merge_20200616_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_tutorial',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
