# Generated by Django 3.0.5 on 2020-06-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0012_room_userlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='userList',
            new_name='user_list',
        ),
    ]
