# Generated by Django 3.0.5 on 2020-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0013_auto_20200627_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
