# Generated by Django 3.0.5 on 2020-07-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainwriting', '0012_auto_20200630_0001'),
        ('brainwriting', '0014_response_user_id'),
    ]

    operations = [
    ]
